/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santanu
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    DefaultTableModel model;
    
    public dashboard() {
        initComponents();
        setStudentDetailsToTable();
        setBookDetailsToTable();
        setDataToCards();
    }
    
    
    //display data in table from database
     public void setStudentDetailsToTable(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lms?useTimezone=true&serverTimezone=UTC","root","");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM student_details");
             
             while(rs.next()){
                 String studentId = rs.getString("student_id");
                 String studentName = rs.getString("name");
                 String course = rs.getString("course");
                 String clas = rs.getString("class");
                 
                 
                 Object[] obj = {studentId,studentName,course,clas};
                 model= (DefaultTableModel) tbl_studentDetails.getModel();
                 model.addRow(obj);
                 
             
             }
             
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
     
     //display data in table from database
    
    public void setBookDetailsToTable(){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection   con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lms?useTimezone=true&serverTimezone=UTC","root","");
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM book_details");
             
             while(rs.next()){
                 String bookId = rs.getString("book_id");
                 String bookName = rs.getString("book_name");
                 String author = rs.getString("author");
                 String clas = rs.getString("class");
                 String quantity = rs.getString("quantity");
                 
                 Object[] obj = {bookId,bookName,author,clas,quantity};
                 model= (DefaultTableModel) tbl_bookDetails.getModel();
                 model.addRow(obj);
                 
             
             }
             
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    
    //data show in cards
    
    public  void setDataToCards(){
    
        Statement st = null;
        ResultSet rs = null;
        
        long L = System.currentTimeMillis();
        Date todaysDate = new Date(L);
        
        try {
            Connection con = LMS.getConnection();
            st=con.createStatement();
            rs = st.executeQuery("SELECT * From book_details");
            rs.last();
            lbl_noOfBooks.setText(Integer.toString(rs.getRow()));
            
            
            rs = st.executeQuery("SELECT * From student_details");
            rs.last();
             lbl_noOfStudents.setText(Integer.toString(rs.getRow()));
             
                         
            rs = st.executeQuery("SELECT * From issue_book_details WHERE status = '"+"pending"+"'");
            rs.last();
            lbl_issueBook.setText(Integer.toString(rs.getRow()));
            
            
            rs = st.executeQuery("SELECT * From issue_book_details WHERE due_date < '"+"todaysDate"+"' and status = '"+"pending"+"'");
            rs.last();
            lbl_defaulterList.setText(Integer.toString(rs.getRow()));
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_bookDetails = new rojeru_san.complementos.RSTableMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentDetails = new rojeru_san.complementos.RSTableMetro();
        jLabel21 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_defaulterList = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_issueBook = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_noOfStudents = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_noOfBooks = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonHover18 = new rojerusan.RSButtonHover();
        rSButtonHover10 = new rojerusan.RSButtonHover();
        rSButtonHover11 = new rojerusan.RSButtonHover();
        rSButtonHover12 = new rojerusan.RSButtonHover();
        rSButtonHover14 = new rojerusan.RSButtonHover();
        rSButtonHover15 = new rojerusan.RSButtonHover();
        rSButtonHover16 = new rojerusan.RSButtonHover();
        rSButtonHover17 = new rojerusan.RSButtonHover();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        rSButtonHover3 = new rojerusan.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        rSButtonHover6 = new rojerusan.RSButtonHover();
        rSButtonHover7 = new rojerusan.RSButtonHover();
        rSButtonHover8 = new rojerusan.RSButtonHover();
        rSButtonHover9 = new rojerusan.RSButtonHover();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Book Details");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 190, 40));

        tbl_bookDetails.setForeground(new java.awt.Color(102, 102, 102));
        tbl_bookDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author", "Class", "Quantity"
            }
        ));
        tbl_bookDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tbl_bookDetails.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        tbl_bookDetails.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tbl_bookDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_bookDetails.setColorSelBackgound(new java.awt.Color(255, 153, 102));
        tbl_bookDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tbl_bookDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        tbl_bookDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        tbl_bookDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_bookDetails.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_bookDetails.setRowHeight(30);
        jScrollPane2.setViewportView(tbl_bookDetails);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 750, 130));

        tbl_studentDetails.setForeground(new java.awt.Color(102, 102, 102));
        tbl_studentDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Course", "Class"
            }
        ));
        tbl_studentDetails.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tbl_studentDetails.setColorBordeFilas(new java.awt.Color(102, 102, 102));
        tbl_studentDetails.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tbl_studentDetails.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tbl_studentDetails.setColorSelBackgound(new java.awt.Color(255, 153, 102));
        tbl_studentDetails.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        tbl_studentDetails.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        tbl_studentDetails.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        tbl_studentDetails.setFuenteHead(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        tbl_studentDetails.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_studentDetails.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_studentDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 750, 130));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Student Details");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 40));

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 51, 51)));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterList.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        lbl_defaulterList.setForeground(new java.awt.Color(102, 102, 102));
        lbl_defaulterList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_defaulterList.setText(" 10");
        jPanel5.add(lbl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 170, 90));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Defaulter List");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 160, 40));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 51, 51)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issueBook.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        lbl_issueBook.setForeground(new java.awt.Color(102, 102, 102));
        lbl_issueBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_50px.png"))); // NOI18N
        lbl_issueBook.setText(" 10");
        jPanel4.add(lbl_issueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 170, 90));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Issued Books");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 160, 40));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("No. Of Students");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 40));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 51, 51)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noOfStudents.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        lbl_noOfStudents.setForeground(new java.awt.Color(102, 102, 102));
        lbl_noOfStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_People_50px.png"))); // NOI18N
        lbl_noOfStudents.setText(" 10");
        jPanel3.add(lbl_noOfStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 170, 90));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(51, 51, 51)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noOfBooks.setFont(new java.awt.Font("Segoe UI Black", 1, 40)); // NOI18N
        lbl_noOfBooks.setForeground(new java.awt.Color(102, 102, 102));
        lbl_noOfBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_Shelf_50px.png"))); // NOI18N
        lbl_noOfBooks.setText(" 10");
        jPanel2.add(lbl_noOfBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 170, 90));

        jPanel1.setBackground(new java.awt.Color(72, 61, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 7, 40));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("No. Of Books");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 160, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 465, 30, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 30, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 20, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 30, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 30, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Books_26px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 30, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Book_26px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/Matte-Library-icon.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 40));

        rSButtonHover18.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover18.setText("             Return Books");
        rSButtonHover18.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover18.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover18.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover18ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 236, -1));

        rSButtonHover10.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover10.setText("             View Records");
        rSButtonHover10.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover10.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover10.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover10ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 236, -1));

        rSButtonHover11.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover11.setText("             Default List");
        rSButtonHover11.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover11.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover11.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover11ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 236, -1));

        rSButtonHover12.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover12.setText("             Manage Students");
        rSButtonHover12.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover12.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover12.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover12ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 236, -1));

        rSButtonHover14.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover14.setText("             View Issued Books");
        rSButtonHover14.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover14.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover14.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover14ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 236, -1));

        rSButtonHover15.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover15.setText("             Issue Books");
        rSButtonHover15.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover15.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover15.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover15ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 236, -1));

        rSButtonHover16.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover16.setText("             Logout");
        rSButtonHover16.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover16.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover16.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover16ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 236, -1));

        rSButtonHover17.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover17.setText("             Manage Books");
        rSButtonHover17.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover17.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover17.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover17ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 236, -1));

        rSButtonHover1.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover1.setText("             Dashboard");
        rSButtonHover1.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover1.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover1.setColorTextHover(new java.awt.Color(255, 153, 102));
        rSButtonHover1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Features");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        rSButtonHover2.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover2.setText("    Dashboard");
        rSButtonHover2.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover2.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover2.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover3.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover3.setText("    Dashboard");
        rSButtonHover3.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover3.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover3.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover4.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover4.setText("    Dashboard");
        rSButtonHover4.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover4.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover4.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover5.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover5.setText("    Dashboard");
        rSButtonHover5.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover5.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover5.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover6.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover6.setText("    Dashboard");
        rSButtonHover6.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover6.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover6.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover7.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover7.setText("    Dashboard");
        rSButtonHover7.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover7.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover7.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover8.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover8.setText("    Dashboard");
        rSButtonHover8.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover8.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover8.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        rSButtonHover9.setBackground(new java.awt.Color(101, 106, 109,80));
        rSButtonHover9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Library_26px_1.png"))); // NOI18N
        rSButtonHover9.setText("    Dashboard");
        rSButtonHover9.setColorHover(new java.awt.Color(48, 44, 44,70));
        rSButtonHover9.setColorText(new java.awt.Color(153, 153, 153));
        rSButtonHover9.setColorTextHover(new java.awt.Color(255, 153, 102));
        getContentPane().add(rSButtonHover9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 90, 236, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover12ActionPerformed
          managestudents students = new managestudents();
          students.setVisible(true);
          dispose();
    }//GEN-LAST:event_rSButtonHover12ActionPerformed

    private void rSButtonHover15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover15ActionPerformed
        issuebook book = new issuebook();
        book.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover15ActionPerformed

    private void rSButtonHover17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover17ActionPerformed
        managebooks books = new managebooks();
        books.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover17ActionPerformed

    private void rSButtonHover14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover14ActionPerformed
                                                    
       
        viewissuedbooks issue = new viewissuedbooks();
        issue.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover14ActionPerformed

    private void rSButtonHover11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover11ActionPerformed
               
        defaulterlist list = new defaulterlist();
        list.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover11ActionPerformed

    private void rSButtonHover18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover18ActionPerformed
        returnbook returns = new returnbook();
        returns.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover18ActionPerformed

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        dashboard board = new dashboard();
        board.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void rSButtonHover10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover10ActionPerformed
        viewrecords records = new viewrecords();
        records.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover10ActionPerformed

    private void rSButtonHover16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover16ActionPerformed
       login log = new login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButtonHover16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_defaulterList;
    private javax.swing.JLabel lbl_issueBook;
    private javax.swing.JLabel lbl_noOfBooks;
    private javax.swing.JLabel lbl_noOfStudents;
    private rojerusan.RSButtonHover rSButtonHover1;
    private rojerusan.RSButtonHover rSButtonHover10;
    private rojerusan.RSButtonHover rSButtonHover11;
    private rojerusan.RSButtonHover rSButtonHover12;
    private rojerusan.RSButtonHover rSButtonHover14;
    private rojerusan.RSButtonHover rSButtonHover15;
    private rojerusan.RSButtonHover rSButtonHover16;
    private rojerusan.RSButtonHover rSButtonHover17;
    private rojerusan.RSButtonHover rSButtonHover18;
    private rojerusan.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSButtonHover rSButtonHover6;
    private rojerusan.RSButtonHover rSButtonHover7;
    private rojerusan.RSButtonHover rSButtonHover8;
    private rojerusan.RSButtonHover rSButtonHover9;
    private rojeru_san.complementos.RSTableMetro tbl_bookDetails;
    private rojeru_san.complementos.RSTableMetro tbl_studentDetails;
    // End of variables declaration//GEN-END:variables
}
